// This file is automatically generated. Do not edit it directly.
import type { Database } from "@/types/supabase";
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://vztaiqibajudnjbehgzl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6dGFpcWliYWp1ZG5qYmVoZ3psIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NjQxMjIsImV4cCI6MjA2NTA0MDEyMn0.e_nJ4pB-TwvZtMt8eKXTJuuQ_8dQDM5LMD_SUf5wl-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
